# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oldurosi <oldurosi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/15 02:17:28 by oldurosi          #+#    #+#              #
#    Updated: 2020/02/15 02:45:31 by oldurosi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

run:
	say "Making run files.... Please Wait!!!"
	@gcc -Wall -Wextra -Werror ft_archive.c 
	# @gcc -Wall -Wextra -Werror 
	say "Files made"